"""Provide a class for ODS location list export.

Copyright (c) 2025 Peter Triesberger
For further information see https://github.com/peter88213/novelibre
License: GNU GPLv3 (https://www.gnu.org/licenses/gpl-3.0.en.html)
"""
from nvlib.model.ods.ods_writer import OdsWriter
from nvlib.novx_globals import LOCLIST_SUFFIX
from nvlib.nv_locale import _


class OdsWLocList(OdsWriter):
    """ODS location list templates."""
    DESCRIPTION = _('Location list')
    SUFFIX = LOCLIST_SUFFIX

    _fileHeader = (
        f'{OdsWriter._CONTENT_XML_HEADER}{DESCRIPTION}" '
        'table:style-name="ta1" table:print="false">\n'
        '    <table:table-column table:style-name="co1" '
        'table:visibility="collapse" '
        'table:default-cell-style-name="Default"/>\n'
        '    <table:table-column table:style-name="co3" '
        'table:default-cell-style-name="Default"/>\n'
        '    <table:table-column table:style-name="co4" '
        'table:default-cell-style-name="Default"/>\n'
        '    <table:table-column table:style-name="co2" '
        'table:default-cell-style-name="Default"/>\n'
        '    <table:table-column table:style-name="co3" '
        'table:default-cell-style-name="Default"/>\n'
        '    <table:table-column table:style-name="co4" '
        'table:default-cell-style-name="Default"/>\n'
        '    <table:table-column table:style-name="co1" '
        'table:number-columns-repeated="1013" '
        'table:default-cell-style-name="Default"/>\n'
        '     <table:table-row table:style-name="ro1" '
        'table:visibility="collapse">\n'
        '     <table:table-cell table:style-name="Heading" '
        'office:value-type="string">\n'
        '      <text:p>ID</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell table:style-name="Heading" '
        'office:value-type="string">\n'
        '      <text:p>Name</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell table:style-name="Heading" '
        'office:value-type="string">\n'
        '      <text:p>Description</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell table:style-name="Heading" '
        'office:value-type="string">\n'
        '      <text:p>Aka</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell table:style-name="Heading" '
        'office:value-type="string">\n'
        '      <text:p>Tags</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell table:style-name="Heading" '
        'office:value-type="string">\n'
        '      <text:p>Notes</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell table:style-name="Heading" '
        'table:number-columns-repeated="1013"/>\n'
        '    </table:table-row>\n'
        '     <table:table-row table:style-name="ro1">\n'
        '     <table:table-cell table:style-name="Heading" '
        'office:value-type="string">\n'
        '      <text:p>ID</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell table:style-name="Heading" '
        'office:value-type="string">\n'
        f'      <text:p>{_("Name")}</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell table:style-name="Heading" '
        'office:value-type="string">\n'
        f'      <text:p>{_("Description")}</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell table:style-name="Heading" '
        'office:value-type="string">\n'
        f'      <text:p>{_("Aka")}</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell table:style-name="Heading" '
        'office:value-type="string">\n'
        f'      <text:p>{_("Tags")}</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell table:style-name="Heading" '
        'office:value-type="string">\n'
        f'      <text:p>{_("Notes")}</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell table:style-name="Heading" '
        'table:number-columns-repeated="1013"/>\n'
        '    </table:table-row>\n'
    )
    _locationTemplate = (
        '   <table:table-row table:style-name="ro2">\n'
        '     <table:table-cell office:value-type="string">\n'
        '      <text:p>$ID</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell office:value-type="string">\n'
        '      <text:p>$Title</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell office:value-type="string">\n'
        '      <text:p>$Desc</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell office:value-type="string">\n'
        '      <text:p>$AKA</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell office:value-type="string">\n'
        '      <text:p>$Tags</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell office:value-type="string">\n'
        '      <text:p>$Notes</text:p>\n'
        '     </table:table-cell>\n'
        '     <table:table-cell table:number-columns-repeated="1013"/>\n'
        '    </table:table-row>\n'
    )
    _fileFooter = OdsWriter._CONTENT_XML_FOOTER
